---
services:
  dnsmasq:
    image: mtdcy/dnsmasq:latest
    container_name: dnsmasq
    network_mode: bridge
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      # envs are append after dnsmasq.conf, but its priority is undefined.
      - DNSMASQ_SERVERS="10.10.10.1 114.114.114.114"
      # define dhcp server with gw address, net mask is 255.255.255.0
      - DNSMASQ_DHCP_ROUTER=10.10.10.1
      #- DNSMASQ_DHCP_SERVERS= # dns servers for dhcp
      # more option key=value pairs
      - DNSMASQ_OPTS="--log-facility=-"
    ports: # bridge mode
      - 5353:5353/udp
      - 67:67/udp
    #volumes:
    #  - /path/to/dnsmasq/config:/config
    #healthcheck:
    #  test: curl -x socks5h://127.0.0.1:7070 --fail https://google.com || exit 1
    #  interval: 60s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 60s
