---
services:
  socks5:
    image: ${REGISTRY:-docker.io}/mtdcy/socks5:latest
    container_name: nginx-ui
    hostname: nginx-ui
    network_mode: bridge
    restart: always
    environment:
      - SSH_HOST=user@example.org:22
      - SSH_IDENT=/config/ssh_id_rsa
      - SSH_CONFIG=/config/ssh_config
      - SSH_OPTS=UserKnownHostsFile=/config/ssh_known_hosts
      #- SSH_BIND=0.0.0.0:7070   # work only in host mode
    ports: # bridge mode
      - 7070:1070
    volumes:
      - ${HOME}/.ssh/id_rsa:/config/ssh_id_rsa
    healthcheck:
      test: curl -x socks5h://127.0.0.1:1070 --fail https://google.com
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
