
# musl-gcc.sh has no version control yet
ARG CACHEBUST
RUN <<-EOS
    echo "**** setup musl-gcc ****"
    TARGET="$(uname -m)-linux-musl"

    if curl -fsSI --connect-timeout 1 https://gitea.mtdcy.top -o /dev/null; then
        url=https://gitea.mtdcy.top:8443/mtdcy/musl-gcc-build/releases/download/latest/$TARGET.tar.xz
    else
        url=https://github.com/mtdcy/musl-gcc-build/releases/latest/download/$TARGET.tar.xz
    fi

    curl -fsSL "$url" -o /tmp/$(basename $url)
    tar -C /opt -xf /tmp/$(basename $url)

    # remove share libraries if static one exists
    while read -r so; do
        [[ "$so" =~ libc.so$ ]] && continue

        test -f "${so/%.so/.a}" && rm -fv "$so"* || true
    done < <(find /opt/$TARGET -name "*.so")

    find /opt/$TARGET -name "*.la" -exec rm -rf {} +
EOS

