# final setup: ubuntu

ARG RUST_VERSION=1.98.0
RUN <<-EOS
    echo "**** post setup ****"

    # fix ld-musl
    ln -sfv $(find /opt -name libc.so) /lib/ld-musl-$(uname -m).so.1

    # hack libgcc_s.a => some build system like rustc won't search for libgcc.a
    ln -sfv libgcc.a $(find /opt/ -name libgcc.a | sed 's/libgcc.a$/libgcc_s.a/')

    # fix LD_LIBRARY_PATH
    echo /opt/$(uname -m)-linux-musl/lib > /etc/ld.so.conf.d/$(uname -m)-linux-musl.conf

    # fails on alpine-3, why?
    ldconfig || true

    # testing
    ldconfig -p | grep libc.so
    ldconfig -p | grep libgcc_s.so

    node --version
    gcc --version
    go version

    if which rustup; then
        if test -n "$MIRROR"; then
            export RUSTUP_DIST_SERVER=$MIRROR/rust-static
            export RUSTUP_UPDATE_ROOT=$MIRROR/rust-static/rustup
        fi

        # install toolchain and target(s)
        rustup toolchain install $RUST_VERSION \
            --default \
            --profile minimal \
            --target $(uname -m)-unknown-linux-gnu \
            --target $(uname -m)-unknown-linux-musl \
        
        rustup show

        rustc --version
        cargo --version
    fi

    rm -rf $CARGO_HOME/registry
    rm -rf $CARGO_HOME/*-cache

    # delete default user(1000)
    userdel ubuntu || true
    useradd -U -m -s /bin/bash buildbot

    # no passwd for buildbot
    echo "buildbot ALL=(ALL) NOPASSWD:ALL"  >> /etc/sudoers

    # keep env PATH
    sed -i '/env_reset/ s/^/# &/g' /etc/sudoers
    echo "Defaults !env_reset"              >> /etc/sudoers
    echo "Defaults env_keep += \"PATH\""    >> /etc/sudoers

    sed -i '/secure_path/ s/^/# &/g' /etc/sudoers
    echo "Defaults secure_path=\"$PATH\""   >> /etc/sudoers

    echo 'PS1="[\e[31m${BUILDER_NAME}\e[m] \e[34m\w \e[32m\$\e[m "' >> /home/buildbot/.bashrc
EOS

ARG TARGETPLATFORM
ENV BUILDER_NAME="$TARGETPLATFORM"
