# final setup: wine

# shared wine prefix
ENV WINEPREFIX=/opt/wine
ENV WINEDEBUG=err+module
ENV WINEARCH=win64

# Wine headless mode
ENV DISPLAY=
ENV WINE_MONO_OVERRIDES="1"
ENV WINE_GECKO_OVERRIDES="1"

RUN <<-EOS
    echo "**** setup Wine64 ****"

    # first time run gave an error:
    #   wine: failed to open L"C:\\windows\\syswow64\\rundll32.exe"
    wineboot --init && wineserver -w

    # windows version
    winecfg /v && winecfg /v win10 && winecfg /v

    # headless mode
    wine reg add "HKCU\Software\Wine\Drivers" /v "Graphics" /d "null" /f

    # 删除无用（自启动失败）的服务
    wine reg delete "HKLM\System\CurrentControlSet\Services\MountMgr" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\PlugPlay" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\Eventlog" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\nsiproxy" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\NDIS" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winebth" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winebus" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winehid" /f

    # 禁用 Wine 的崩溃对话框（直接让进程异常退出，不弹窗挂起）
    wine reg add "HKCU\Software\Wine\WineDbg" /v "ShowCrashDialog" /t REG_DWORD /d 0 /f

    #winetricks corefonts
    winetricks vd=off   # virtual desktop
    winetricks nocrashdialog
    winetricks autostart_winedbg=disabled

    # wait until wine is done (write reg and files to disk)
    wineserver -w && wineboot -s

    echo "**** Finish ****"

    # fails on alpine-3, why?
    ldconfig || true

    node --version
    go version

    rm -rf $CARGO_HOME/registry
    rm -rf $CARGO_HOME/*-cache

    # delete default user(1000)
    userdel ubuntu || true
    useradd -U -m -s /bin/bash buildbot

    chown -R buildbot "$WINEPREFIX"

    # no passwd for buildbot
    echo "buildbot ALL=(ALL) NOPASSWD:ALL"  >> /etc/sudoers

    # keep env PATH
    sed -i '/env_reset/ s/^/# &/g' /etc/sudoers
    echo "Defaults !env_reset"              >> /etc/sudoers
    echo "Defaults env_keep += \"PATH\""    >> /etc/sudoers

    sed -i '/secure_path/ s/^/# &/g' /etc/sudoers
    echo "Defaults secure_path=\"$PATH\""   >> /etc/sudoers

    echo 'PS1="[\e[31m${BUILDER_NAME}\e[m] \e[34m\w \e[32m\$\e[m "' >> /home/buildbot/.bashrc
EOS

