
ARG LLVM_MINGW_VERSION=20260616
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN <<-EOS
    echo "**** setup llvm-mingw ****"
    curl_opts=(
        -fvSL
        # 伪装浏览器请求（防止被防火墙拦截）
        -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    )

    # 防止被Github拦截
    test -z "${GITHUB_TOKEN}" || curl_opts+=( -H "Authorization: Bearer ${GITHUB_TOKEN}" )

    platform=$(uname -m)
    curl "${curl_opts[@]}" https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_VERSION/llvm-mingw-$LLVM_MINGW_VERSION-ucrt-ubuntu-22.04-$platform.tar.xz | tar -xJ --strip-components=1

    # 清理不需要的架构
    for arch in *-w64-mingw32; do
        [ "$arch" = "generic-w64-mingw32" ] && continue # 所有架构共享的公共核心资产库
        [ "$arch" = "$platform-w64-mingw32" ] && continue # 当前架构
        rm -rf "$arch"
        rm -f "bin/$arch"*
    done
EOS

