---
services:
  nginx:
    image: ${REGISTRY:-docker.io}/mtdcy/nginx-ui:latest
    container_name: nginx-ui
    hostname: nginx-ui
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - UMASK=022
    volumes:
      - ./nginx:/etc/nginx # site config
      - ./ui:/etc/nginx-ui
      - /var/log:/var/log
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # mgmt port
    restart: always
    healthcheck:
      test: curl --fail -o /dev/null http://localhost:8080
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
