# syntax=docker/dockerfile:1
FROM baseimage:latest

# labels
LABEL maintainer="mtdcy.chen@gmail.com"

ARG NGX_VER=1.30.4

# Tested version
ARG NGX_UI_VER=2.5.7

ARG CACHEBUST=1
ARG TARGETPLATFORM

ENV PATH="/opt/bin:$PATH"

COPY rootfs/ /

SHELL ["bash", "-c"]
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN <<-EOS
    set -ex
    echo "**** prepare nginx runtimes ****"

    if which apt-get; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y cron logrotate goaccess

        apt-get autoremove
        apt-get clean
        rm -rf /var/lib/apt/lists/*
    else
        apk update
        apk add --no-cache cronie logrotate goaccess

        # php-fpm
        apk add --no-cache php php-fpm php-fileinfo file
        ln -sfv /usr/sbin/php-fpm* /usr/sbin/php-fpm || true

        # alpine has different crontab names
        which crond && ln -sfv $(which crond) /usr/sbin/cron || true
    fi

    # goaccess: share the same conf dir with nginx
    mv /etc/goaccess/* /etc/nginx/ || true
    rm -rf /etc/goaccess || true

    # no default crontab for logrotate
    rm -rf /etc/cron.*

    echo "**** prepare nginx ****"
    mkdir -pv /opt/bin
    curl -fvSL http://cmdlets.mtdcy.top/latest/cmdlets.sh -o /opt/bin/cmdlets.sh
    chmod a+x /opt/bin/cmdlets.sh

    cmdlets.sh install nginx@$NGX_VER

    echo "**** prepare nginx-ui ****"

    TARGET="linux-64"
    case "$TARGETPLATFORM" in
        linux/arm64)    TARGET=linux-arm64-v8a ;;
    esac

    curl_opts=(
        -fvSL
        # 伪装浏览器请求（防止被防火墙拦截）
        -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    )

    # 防止被Github拦截
    test -z "${GITHUB_TOKEN}" || curl_opts+=( -H "Authorization: Bearer ${GITHUB_TOKEN}" )

    #curl "${curl_opts[@]}" https://github.com/0xJacky/nginx-ui/releases/latest/download/nginx-ui-${TARGET,,}.tar.gz | tar -C /usr/bin/ -xz nginx-ui
    curl "${curl_opts[@]}" https://github.com/0xJacky/nginx-ui/releases/download/v$NGX_UI_VER/nginx-ui-${TARGET,,}.tar.gz | tar -C /opt/bin/ -xz nginx-ui

    echo "**** finish ****"

    # fails on alpine
    ldconfig || true

    nginx -V
    nginx-ui -version

    mv /etc/nginx /etc/nginx.default

    # add user if not exists
    groupadd www-data || true
    useradd -g www-data -m -s /sbin/nologin www-data || true
EOS

# 8080 for mgmt, 7890 for goaccess
EXPOSE  80 443 8080 7890

VOLUME /etc/nginx /var/www /var/log

ENTRYPOINT ["/entrypoint.sh"]

# vim:ft=dockerfile
