---
services:
  p910nd:
    image: mtdcy/p910nd:latest
    container_name: p910nd
    network_mode: bridge
    restart: always
    ports:
      - "9100:9100"
    environment:
      - TZ="Asia/Shanghai"
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
