#!/bin/bash
# 
# MSYS2 Shell

export MSYSTEM=${MSYSTEM:-MSYS}
export XVFB_RUN=${XVFB_RUN:-0}

# MSYS2 will set OSTYPE value
# https://linux.die.net/man/1/bash
unset OSTYPE

# always start a login shell, or MSYS2 settings won't work
if [ "$XVFB_RUN" -ne 0 ]; then
    xvfb-run -a wine bash.exe -l "$@"
else
    wine bash.exe -l "$@"
fi
