# syntax=docker/dockerfile:1

FROM baseimage:latest AS builder

ARG NODE_VERSION=v24
ARG GO_VERSION=1.26.7
ARG RUST_VERSION=1.98.0

ARG MIRROR=
ARG TARGETPLATFORM

COPY --chmod=0755 entrypoint.sh /opt/

COPY ./scripts/* /tmp/

WORKDIR /opt/

SHELL ["/bin/bash", "-ex", "-o", "pipefail", "-c"]
RUN <<-EOS
    node --version | grep "$NODE_VERSION" && exit 0 || true

    echo "**** setup nodejs ****"
    # node prebuilts only for glibc
    IFS=' ' read -r version _ < <(curl -sL https://nodejs.org/dist/index.tab | grep -oE "^$NODE_VERSION[0-9.]+" -m1)
    case "$TARGETPLATFORM" in
      linux/arm64)
        curl -fsSL "https://nodejs.org/dist/$version/node-$version-linux-arm64.tar.xz" | tar -xJ --strip-components=1
      ;;
      linux/amd64)
        curl -fsSL "https://nodejs.org/dist/$version/node-$version-linux-x64.tar.xz" | tar -xJ --strip-components=1
      ;;
    esac
EOS

RUN <<-EOS
    echo "**** setup golang ****"
    #goversion=$(curl -s "https://go.dev/VERSION?m=text" | grep "^go")
    curl -fsSL https://go.dev/dl/go$GO_VERSION.${TARGETPLATFORM//\//-}.tar.gz | tar -xz
EOS

RUN <<-EOS
    echo "**** setup rust ****"
    export CARGO_HOME=/opt/cargo
    export RUSTUP_HOME=/opt/rustup
    export PATH="$CARGO_HOME/bin:$PATH"

    if test -n "$MIRROR"; then
        export RUSTUP_DIST_SERVER=$MIRROR/rust-static
        export RUSTUP_UPDATE_ROOT=$MIRROR/rust-static/rustup
    fi

    /tmp/rustup-init.sh -y --no-modify-path     \
        --profile minimal                       \
        --default-toolchain $RUST_VERSION

    rustup target add --toolchain=$RUST_VERSION $(uname -m)-pc-windows-gnu
EOS

# cygwin-gcc has no version control yet
ARG CACHEBUST
RUN <<-EOS
    echo "**** setup cygwin-gcc ****"

    if curl -fsSI --connect-timeout 1 https://gitea.mtdcy.top -o /dev/null; then
        url=https://gitea.mtdcy.top/mtdcy/cygwin-gcc-build/releases/download/latest/$TARGET.tar.xz
    else
        url=https://github.com/mtdcy/cygwin-gcc-build/releases/latest/download/$TARGET.tar.xz
    fi

    curl -fsSL "$url" | tar -xJ -C /opt
    
    find /opt -name "*.la" -exec rm -rf {} +
EOS

FROM baseimage:latest

# labels
LABEL maintainer="mtdcy.chen@gmail.com"

WORKDIR /opt/
SHELL ["/bin/bash", "-ex", "-o", "pipefail", "-c"]

RUN <<-EOS
    echo "**** install essentials ****"

    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y \
        wget curl git diffutils findutils ncurses-bin \
        tar gzip xz-utils lzip unzip zstd \
        libtool automake autoconf autopoint \
        cmake meson pkg-config \
        texinfo gettext moreutils \
        nasm yasm bison flex \
        luajit perl libhttp-daemon-perl \
        python3 python3-pip python3-venv \
        openssh-client rsync \
        libssl-dev
    apt-get clean
    rm -rf /var/lib/apt/lists/* /var/tmp/* /var/log/*

    echo "**** install latest meson ****"
    python3 -m pip install --upgrade pip || true
    # --break-system-packages: This environment is externally managed
    python3 -m pip install --upgrade meson --break-system-packages
    rm -rf "$HOME/.cache" || true
EOS

# install builder tools
COPY --from=builder /opt /opt

# must set these ENVs explicitly, or run container with --entrypoint='' will have problem
ENV GOROOT="/opt/go"
ENV CARGO_HOME="/opt/cargo"
ENV RUSTUP_HOME="/opt/rustup"
ENV PATH="$CARGO_HOME/bin:$GOROOT/bin:/opt/bin:$PATH"

# shared wine prefix
ENV WINEPREFIX=/opt/wine
ENV WINEDEBUG=err+module
ENV WINEARCH=win64

# Wine headless mode
ENV DISPLAY=
ENV WINE_MONO_OVERRIDES="1"
ENV WINE_GECKO_OVERRIDES="1"

RUN <<-EOS
    echo "**** setup Wine64 ****"

    # first time run gave an error:
    #   wine: failed to open L"C:\\windows\\syswow64\\rundll32.exe"
    wineboot --init && wineserver -w

    # windows version
    winecfg /v && winecfg /v win10 && winecfg /v

    # headless mode
    wine reg add "HKCU\Software\Wine\Drivers" /v "Graphics" /d "null" /f

    # 删除无用（自启动失败）的服务
    wine reg delete "HKLM\System\CurrentControlSet\Services\MountMgr" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\PlugPlay" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\Eventlog" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\nsiproxy" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\NDIS" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winebth" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winebus" /f
    wine reg delete "HKLM\System\CurrentControlSet\Services\winehid" /f

    # 禁用 Wine 的崩溃对话框（直接让进程异常退出，不弹窗挂起）
    wine reg add "HKCU\Software\Wine\WineDbg" /v "ShowCrashDialog" /t REG_DWORD /d 0 /f

    #winetricks corefonts
    winetricks vd=off   # virtual desktop
    winetricks nocrashdialog
    winetricks autostart_winedbg=disabled

    # wait until wine is done (write reg and files to disk)
    wineserver -w && wineboot -s

    echo "**** Finish ****"

    # fails on alpine-3, why?
    ldconfig || true

    $(uname -m)-pc-cygwin-gcc --version
    node --version
    go version
    cargo --version
    rustc --version

    rm -rf $CARGO_HOME/registry
    rm -rf $CARGO_HOME/*-cache

    # delete default user(1000)
    userdel ubuntu || true
    useradd -U -m -s /bin/bash buildbot

    chown -R buildbot "$WINEPREFIX"

    # no passwd for buildbot
    echo "buildbot ALL=(ALL) NOPASSWD:ALL"  >> /etc/sudoers

    # keep env PATH
    sed -i '/env_reset/ s/^/# &/g' /etc/sudoers
    echo "Defaults !env_reset"              >> /etc/sudoers
    echo "Defaults env_keep += \"PATH\""    >> /etc/sudoers

    sed -i '/secure_path/ s/^/# &/g' /etc/sudoers
    echo "Defaults secure_path=\"$PATH\""   >> /etc/sudoers

    echo 'PS1="[\e[31m${BUILDER_NAME}\e[m] \e[34m\w \e[32m\$\e[m "' >> /home/buildbot/.bashrc
EOS

# override entrypoint
ENTRYPOINT ["/opt/entrypoint.sh"]

ARG TARGETPLATFORM
ENV BUILDER_NAME="${TARGETPLATFORM//linux/cygwin}"
