# syntax=docker/dockerfile:1

FROM baseimage:latest AS builder

ARG NODE_VERSION=v24
ARG GO_VERSION=1.26.7
ARG RUST_VERSION=1.98.0
ARG LLVM_MINGW_VERSION=20260616

ARG MIRROR=
ARG TARGETPLATFORM

COPY --chmod=0755 entrypoint.sh /opt/

COPY ./scripts/* /tmp/

WORKDIR /opt/

SHELL ["/bin/bash", "-ex", "-o", "pipefail", "-c"]
RUN <<-EOS
    echo "**** setup nodejs ****"
    # node prebuilts only for glibc
    if ldd --version | grep GLIBC; then
        # LTS: v24
        IFS=' ' read -r version _ < <(curl -sL https://nodejs.org/dist/index.tab | grep -oE "^$NODE_VERSION[0-9.]+" -m1)
        case "$TARGETPLATFORM" in
          linux/arm64)
            curl -fsSL "https://nodejs.org/dist/$version/node-$version-linux-arm64.tar.xz" | tar -xJ --strip-components=1
          ;;
          linux/amd64)
            curl -fsSL "https://nodejs.org/dist/$version/node-$version-linux-x64.tar.xz" | tar -xJ --strip-components=1
          ;;
        esac
    fi
EOS

RUN <<-EOS
    echo "**** setup golang ****"
    #goversion=$(curl -s "https://go.dev/VERSION?m=text" | grep "^go")
    curl -fsSL https://go.dev/dl/go$GO_VERSION.${TARGETPLATFORM//\//-}.tar.gz | tar -xz
EOS

RUN <<-EOS
    echo "**** setup rust ****"
    export CARGO_HOME=/opt/cargo
    export RUSTUP_HOME=/opt/rustup
    export PATH="$CARGO_HOME/bin:$PATH"

    if test -n "$MIRROR"; then
        export RUSTUP_DIST_SERVER=$MIRROR/rust-static
        export RUSTUP_UPDATE_ROOT=$MIRROR/rust-static/rustup
    fi

    /tmp/rustup-init.sh -y --no-modify-path     \
        --profile minimal                       \
        --default-toolchain $RUST_VERSION

    rustup target add --toolchain=$RUST_VERSION $(uname -m)-pc-windows-gnullvm

    echo "**** setup cargo ****"
    apt-get update
    apt-get install -y gcc libssl-dev pkg-config

    if test -n "$MIRROR"; then
    cat << EOF >> "$CARGO_HOME/config.toml"
[source.crates-io]
replace-with = 'crates-io-mirrors'

[source.crates-io-mirrors]
registry = "sparse+$MIRROR/crates.io-index/"
EOF
    fi

    # install host tools: cargo-c
    cargo install cargo-c
    rm -rf $CARGO_HOME/{registry,git,config.toml}
EOS

FROM baseimage:latest

# labels
LABEL maintainer="mtdcy.chen@gmail.com"

WORKDIR /opt/
SHELL ["/bin/bash", "-ex", "-o", "pipefail", "-c"]
RUN <<-EOS
    echo "**** install essentials ****"

    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y \
        wget curl git diffutils findutils ncurses-bin \
        tar gzip xz-utils lzip unzip zstd \
        mingw-w64 binutils-mingw-w64 mingw-w64-tools \
        libtool automake autoconf autopoint \
        cmake meson texinfo gettext moreutils \
        nasm yasm bison flex \
        luajit perl libhttp-daemon-perl \
        python3 python3-pip python3-venv \
        openssh-client rsync \
        libssl-dev
    apt-get clean
    rm -rf /var/lib/apt/lists/* /var/tmp/* /var/log/*

    echo "**** install latest meson ****"
    python3 -m pip install --upgrade pip || true
    # --break-system-packages: This environment is externally managed
    python3 -m pip install --upgrade meson --break-system-packages
    rm -rf "$HOME/.cache" || true
EOS

COPY --from=builder /opt /opt

# must set these ENVs explicitly, or run container with --entrypoint='' will have problem
ENV GOROOT="/opt/go"
ENV CARGO_HOME="/opt/cargo"
ENV RUSTUP_HOME="/opt/rustup"
ENV PATH="$CARGO_HOME/bin:$GOROOT/bin:/opt/bin:$PATH"

ENV WINEDEBUG=err+module

# 00a4:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\winebth": c0000142
# 003c:fixme:service:scmdatabase_autostart_services Auto-start service L"winebth" failed to start: 1114
ENV WINEDLLOVERRIDES="winebth.dll="

RUN <<-EOS
    # first time run gave an error:
    #   wine: failed to open L"C:\\windows\\syswow64\\rundll32.exe"
    winecfg || true

    echo "**** post setup ****"

    # fails on alpine-3, why?
    ldconfig || true

    $(uname -m)-w64-mingw32-gcc --version
    node --version
    go version
    cargo --version
    rustc --version

    rm -rf $CARGO_HOME/registry
    rm -rf $CARGO_HOME/*-cache

    # delete default user(1000)
    userdel ubuntu || true
    useradd -U -m -s /bin/bash buildbot

    chown -R buildbot "$WINEPREFIX"

    # no passwd for buildbot
    echo "buildbot ALL=(ALL) NOPASSWD:ALL"  >> /etc/sudoers

    # keep env PATH
    sed -i '/env_reset/ s/^/# &/g' /etc/sudoers
    echo "Defaults !env_reset"              >> /etc/sudoers
    echo "Defaults env_keep += \"PATH\""    >> /etc/sudoers

    sed -i '/secure_path/ s/^/# &/g' /etc/sudoers
    echo "Defaults secure_path=\"$PATH\""   >> /etc/sudoers

    echo 'PS1="[\e[31m${BUILDER_NAME}\e[m] \e[34m\w \e[32m\$\e[m "' >> /home/buildbot/.bashrc
EOS

# override entrypoint
ENTRYPOINT ["/opt/entrypoint.sh"]

ARG TARGETPLATFORM
ENV BUILDER_NAME="${TARGETPLATFORM//linux/mingw}"
