---
services:
  basic:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    environment:
      - REMOTE_HOST=user@example.org:22
      - DNSMASQ_SERVER=8.8.8.8
    volumes:
      - ./basic:/config
      - ~/.ssh:/config/ssh
    ports:
      - 7070:1070
      - 5353:53/tcp
      - 5353:53/udp
