---
services:
  basic:
    image: ip2route:latest
    container_name: ip2route-basic
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    environment:
      - REMOTE_HOST=user@example.org:22
      - DNSMASQ_SERVER=8.8.8.8
    volumes:
      - ./ip2route-basic:/config
      - ~/.ssh:/config/ssh
    ports:
      - 7070:1070
      - 5353:53/tcp
      - 5353:53/udp
    healthcheck:  # runs inside container
      test: curl --fail -sI -x socks5h://127.0.0.1:1070 https://google.com || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
