---
services:
  ip2route:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - MODE=route
      - REMOTE_HOST=user@remote:22
      - LOCAL_ADDR=10.1.1.110
      - REMOTE_TUN=1
      #- DNSMASQ_INTERFACE=br0
      - DNSMASQ_SERVER=10.10.10.1
    volumes:
      - .:/config
      - ~/.ssh:/config/ssh
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:  # runs inside container
      test: curl --fail -sI -x socks5h://127.0.0.1:1070 https://google.com || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
