---
services:
  ip2route:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - MODE=route
      - REMOTE_HOST=user@remote:22
      - LOCAL_ADDR=10.1.1.110/24
      - REMOTE_ADDR=10.1.1.1
      - REMOTE_DEVICE=tun1
      #- DNSMASQ_INTERFACE=br0
      - DNSMASQ_SERVER=10.10.10.10
    volumes:
      - .:/config
      - ~/.ssh:/config/ssh
    devices:
      - /dev/net/tun:/dev/net/tun
