---
services:
  ip2route:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true  # need by sysctl
    environment:
      - MODE=route
      - REMOTE_HOST=n2n://community@example.org:7654
      - LOCAL_ADDR=10.0.0.110/24
      - REMOTE_ADDR=10.0.0.1
      - LOCAL_DEVICE=n2n0
    volumes:
      - ./n2n:/config
      - ./data:/config/data
    devices:
      - /dev/net/tun:/dev/net/tun
