---
services:
  ip2route:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - MODE=route
      - REMOTE_HOST=n2n://b9ee86ef6b7592ee@ecs.mtdcy.top:6789
      - N2N_ADDR=10.0.0.110/24
      - N2N_REMOTE=10.0.0.1
      - N2N_OPTS=-S2
    volumes:
      - ./n2n:/config
      - ./data:/config/data
      - ~/.ssh:/config/ssh
    devices:
      - /dev/net/tun:/dev/net/tun
