---
services:
  serve:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - MODE=serve
      - LOCAL_ADDR=10.1.1.1/24
      - LOCAL_DEVICE=tun1  # tun0 reserved
      - DEVICE_COUNT=3
      - DNSMASQ_SERVER=8.8.8.8
    volumes:
      - ./serve:/config
    devices:
      - /dev/net/tun:/dev/net/tun
