---
services:
  serve:
    image: ip2route:latest
    container_name: ip2route-serve
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - MODE=serve
      - LOCAL_ADDR=10.0.1.1
      - LOCAL_TUN=1
      - MAX_TUN=9
      - DNSMASQ_SERVER=8.8.8.8
    volumes:
      - ./serve0:/config
    devices:
      - /dev/net/tun:/dev/net/tun
