---
services:
  serve:
    image: ip2route:latest
    container_name: ip2route
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true  # need by sysctl
    environment:
      - MODE=serve
      - LOCAL_ADDR=10.1.1.1/24
      - LOCAL_DEVICE=tun1  # tun0 reserved
      # dns server
      - DNSMASQ_PORT=1053
      - DNSMASQ_INTERFACE=tun1
      - DNSMASQ_SERVER=8.8.8.8
      # n2n server
      - N2N_DEVICE=n2n0
      - N2N_ADDR=10.1.0.1/24
    volumes:
      - ./serve:/config
    devices:
      - /dev/net/tun:/dev/net/tun
