---
name: Build wine baseimage

on:
  push:
    paths:
      - baseimage/Dockerfile.wine
      - .github/workflows/baseimage-wine.yml

  workflow_dispatch: null

env:
  wine: '11.0'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}

    steps:
      - name: Check
        id: check
        run: |-
          set -ex

          # TODO: find out the latest version
          echo "version=${{ env.wine }}" >> "$GITHUB_OUTPUT"

  wine-latest:
    name: Build wine-latest
    uses: ./.github/workflows/buildx.yml
    needs: prepare
    secrets: inherit
    with:
      runner: ubuntu-latest
      platforms: linux/amd64
      context: baseimage
      dockerfile: baseimage/Dockerfile.wine
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-${{ needs.prepare.outputs.version }}
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
      args: |-
        MIRROR=${{ vars.MIRRORS }}
        WINE=https://dl.winehq.org/wine/source/${{ needs.prepare.outputs.version }}/wine-${{ needs.prepare.outputs.version }}.tar.xz
