name: Build baseimage

on:
  push:
    paths:
      - baseimage/Dockerfile
      - .github/workflows/baseimage.yml

jobs:
  build-baseimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: https://git.mtdcy.top/actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup buildx
        if: ${{ vars.LOCAL_REGISTRY == '' }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3
        with:
          driver-opts:
            network=host
          cleanup: true

      - name: Setup buildx (local registry)
        if: ${{ vars.LOCAL_REGISTRY }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3
        with:
          driver-opts:
            network=host
          cleanup: true
          buildkitd-config-inline: |
            debug = true
            [registry."${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."docker.io"]
              mirrors = ["registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.io"]
              mirrors = ["ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.io"]
              mirrors = ["lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true

      - name: Build and Push (24.04/latest)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        with:
          context: baseimage
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04
          file: baseimage/Dockerfile
          build-args: |
            BASEIMAGE=ubuntu:24.04
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:buildcache,mode=max

      - name: Build and Push (22.04)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        with:
          context: baseimage
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-22.04
          file: baseimage/Dockerfile
          build-args: |
            BASEIMAGE=ubuntu:22.04
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:buildcache,mode=max

  build-builder:
    uses: ./.github/workflows/builder.yml
    needs: [build-baseimage]

  build-nginx:
    uses: ./.github/workflows/nginx.yml
    needs: [build-baseimage]

  build-printer:
    uses: ./.github/workflows/printer.yml
    needs: [build-baseimage]
