---
name: Build wine msys2

on:
  push:
    paths:
      - baseimage/Dockerfile.wine
      - baseimage/Dockerfile.msys2
      - baseimage/wine/**
      - baseimage/msys2
      - .github/workflows/baseimage-wine-msys2.yml

  workflow_dispatch: null

# env is unavailable under jobs.<job_id>.with.<with_id>

jobs:
  wine:
    name: Build wine
    uses: ./.github/workflows/buildx.yml
    secrets: inherit
    strategy:
      matrix:
        wine_url:
          - https://gitlab.winehq.org/jhol/wine.git
        wine_tag:
          - msys2-hacks-21
    with:
      runner: ubuntu-latest
      platforms: linux/amd64
      context: baseimage
      dockerfile: baseimage/Dockerfile.wine
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-${{ matrix.wine_tag }}
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
      args: |-
        MIRROR=${{ vars.MIRRORS }}
        WINE_REPO=${{ matrix.wine_url }}#${{ matrix.wine_tag }}

  msys2:
    name: Build msys
    needs: wine
    uses: ./.github/workflows/buildx.yml
    secrets: inherit
    strategy:
      matrix:
        msys2:
          - 20250830
    with:
      runner: ubuntu-latest
      platforms: linux/amd64
      context: baseimage
      dockerfile: baseimage/Dockerfile.msys2
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:msys2-${{ matrix.msys2 }}
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:msys2-latest
      args: |-
        MIRROR=${{ vars.MIRRORS }}
        MSYS2_VERSION=${{ matrix.msys2 }}
