---
name: Build baseimage

on:
  push:
    paths:
      - baseimage/Dockerfile
      - baseimage/Dockerfile.wine
      - .github/workflows/baseimage.yml

  workflow_dispatch:

jobs:
  build:
    name: Build baseimage
    runs-on: ubuntu-latest

    # 向 buildx 走私 vars/secrets
    env:
      MIRRORS: ${{ vars.MIRRORS }}
      REGISTRY: ${{ vars.REGISTRY }}
      REGISTRY_USER: ${{ vars.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Build ubuntu-24.04
        uses: ./.github/actions/buildx
        with:
          context: baseimage
          baseimage: ubuntu:24.04
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04

      - name: Build ubuntu-22.04
        uses: ./.github/actions/buildx
        with:
          context: baseimage
          baseimage: ubuntu:22.04
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-22.04

      - name: Build alpine-3
        uses: ./.github/actions/buildx
        with:
          context: baseimage
          baseimage: alpine:3
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-3

      - name: Build wine
        uses: ./.github/actions/buildx
        with:
          context: baseimage
          platforms: linux/amd64
          dockerfile: baseimage/Dockerfile.wine
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04
          tags: |-
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-11.0
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
