name: Build builder-alpine

on:
  push:
    paths:
      - builder/Dockerfile.alpine
      - .github/workflows/builder-alpine.yml

  workflows_run:
    workflows: [Build baseimage-alpine]
    types:
      - completed

jobs:
  build-builder-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: https://git.mtdcy.top/actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup buildx
        if: ${{ vars.LOCAL_REGISTRY == '' }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3
        with:
          driver-opts:
            network=host
          cleanup: true

      - name: Setup buildx (local registry)
        if: ${{ vars.LOCAL_REGISTRY }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3
        with:
          driver-opts:
            network=host
          cleanup: true
          buildkitd-config-inline: |
            debug = true
            [registry."${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."docker.io"]
              mirrors = ["registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.io"]
              mirrors = ["ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.io"]
              mirrors = ["lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true

      - name: Build and Push
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        with:
          context: builder
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-24.04
          file: builder/Dockerfile.alpine
          build-args: |
            BASEIMAGE=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-latest
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:buildcache,mode=max
