---
name: Build builder

on:
  push:
    paths:
      - builder/Dockerfile.mingw64
      - builder/entrypoint.sh
      - builder/resources/**
      - .github/workflows/builder-mingw64.yml

  # update rust toolchain and others weekly
  schedule:
    - cron: '0 0 * * 2'  # weekly

# workflows_run:
#   workflows: [Build baseimage]
#   types:
#     - completed

  workflow_call: null

  workflow_dispatch: null

jobs:
  mingw64-latest:
    name: Build mingw64-latest
    uses: ./.github/workflows/buildx.yml
    secrets: inherit
    with:
      runner: ubuntu-latest
      platforms: linux/amd64
      context: builder
      dockerfile: builder/Dockerfile.mingw64
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:mingw64-latest
      args: |-
        MIRROR=${{ vars.MIRRORS }}
