---
name: Build builder

on:
  push:
    paths:
      - builder/Dockerfile
      - builder/entrypoint.sh
      - builder/Implib.so
      - .github/workflows/builder.yml

  # update rust toolchain and others weekly
  schedule:
    - cron: '0 0 * * 1'  # weekly

# workflows_run:
#   workflows: [Build baseimage]
#   types:
#     - completed

  workflow_call: null

  workflow_dispatch: null

jobs:
  ubuntu-2404:
    name: Build ubuntu-24.04-${{ matrix.arch }} on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    uses: ./.github/workflows/buildx.yml
    secrets: inherit
    with:
      runner: ${{ matrix.os }}
      platforms: linux/${{ matrix.arch }}
      context: builder
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04-${{ matrix.arch }}
      args: |-
        MIRROR=${{ vars.MIRRORS }}

  ubuntu-2204:
    name: Build ubuntu-22.04-${{ matrix.arch }} on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    uses: ./.github/workflows/buildx.yml
    secrets: inherit
    with:
      runner: ${{ matrix.os }}
      platforms: linux/${{ matrix.arch }}
      context: builder
      baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-22.04
      tags: |
        ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04-${{ matrix.arch }}
      args: |-
        MIRROR=${{ vars.MIRRORS }}

# alpine-3:
#   name: Build alpine-3-${{ matrix.arch }} on ${{ matrix.os }}
#   strategy:
#     matrix:
#       include:
#         - os: ubuntu-24.04
#           arch: amd64
#         - os: ubuntu-24.04-arm
#           arch: arm64
#   uses: ./.github/workflows/buildx.yml
#   secrets: inherit
#   with:
#     runner: ${{ matrix.os }}
#     platforms: linux/${{ matrix.arch }}
#     context: builder
#     baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-3
#     tags: |
#       ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3-${{ matrix.arch }}
#     args: |-
#       MIRROR=${{ vars.MIRRORS }}

  merge-tagged-images:
    runs-on: ubuntu-latest
    needs:
      - ubuntu-2404
      - ubuntu-2204
    steps:
      # need to login and setup registry again
      - name: Login
        env:
          token: ${{ secrets.REGISTRY_TOKEN }}
        if: ${{ env.token != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Merge tagged images
        run: |-
          set -ex

          # ubuntu-latest
          docker manifest create --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-latest      \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04-amd64 \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04-arm64
          docker manifest push   --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-latest

          # ubuntu-24.04|latest
          docker manifest create --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04       \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04-amd64 \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04-arm64
          docker manifest push   --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04

          # ubuntu-22.04
          docker manifest create --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04       \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04-amd64 \
                                    --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04-arm64
          docker manifest push   --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04

#         # alpine-latest
#         docker manifest create --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-latest      \
#                                   --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3-amd64     \
#                                   --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3-arm64
#         docker manifest push   --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-latest

#         # alpine-3
#         docker manifest create --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3           \
#                                   --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3-amd64     \
#                                   --amend ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3-arm64
#         docker manifest push   --insecure ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3
