name: Build and Push

on:
  push:
    paths:
      - baseimage/**
      - nginx/**
      - nginx-ui/**
      - socks5/**
      - printer/**
      - .github/workflows/build-push.yml
    paths-ignore:
      - LICENSE
      - Makefile
      - README.md
      - '**/README.md'
      - '**/compose.yml'

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: https://git.mtdcy.top/actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup buildx
        if: ${{ vars.LOCAL_REGISTRY == '' }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3

      - name: Setup buildx (local registry)
        if: ${{ vars.LOCAL_REGISTRY }}
        uses: https://git.mtdcy.top/actions/docker-setup-buildx@v3
        with:
          buildkitd-config-inline: |
            debug = true
            [registry."${{ vars.LOCAL_REGISTRY }}"]
              http = true
              insecure = true
            [registry."docker.io"]
              http = true
              mirrors = ["registry.${{ vars.LOCAL_REGISTRY }}"]
            [registry."ghcr.io"]
              http = true
              mirrors = ["ghcr.${{ vars.LOCAL_REGISTRY }}"]
            [registry."lscr.io"]
              http = true
              mirrors = ["lscr.${{ vars.LOCAL_REGISTRY }}"]

      - name: Inspect
        id: inspect
        run: |
          docker buildx inspect

          bash --version
          tags() {
            IFS='=' read -r _ v <<< "$(grep 'ARG VERSION=' $1/Dockerfile)"
            IFS='.' read -r m n r <<< "$v"
            t=(
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:latest
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m.$n
            )
            [ -n "$r" ] && t+=(
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m.$n.$r
            )
            echo "$1-tags=$(tr ' ' ',' <<< "${t[*]}")" | tee -a $GITHUB_OUTPUT
          }

          tags nginx
          tags nginx-ui
          tags printer
          tags socks5
        shell: bash

      - name: Build and Push (baseimage:alpine)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: baseimage
          BASEIMAGE: alpine:3
          TAGS: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-3
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max

      - name: Build and Push (baseimage:ubuntu)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: baseimage
          BASEIMAGE: ubuntu:24.04
          TAGS: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max

      - name: Build and Push (nginx)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: nginx
          TAGS: ${{ steps.inspect.outputs.nginx-tags }}
          BASEIMAGE: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max

      - name: Build and Push (nginx-ui)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: nginx-ui
          TAGS: ${{ steps.inspect.outputs.nginx-ui-tags }}
          BASEIMAGE: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:latest
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max

      - name: Build and Push (socks5)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: socks5
          TAGS: ${{ steps.inspect.outputs.socks5-tags }}
          BASEIMAGE: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-latest
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max

      - name: Build and Push (printer)
        uses: https://git.mtdcy.top/actions/docker-build-push@v6
        env:
          PROJECT: printer
          TAGS: ${{ steps.inspect.outputs.printer-tags }}
          BASEIMAGE: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
        with:
          context: ${{ env.PROJECT }}
          push: true
          tags: ${{ env.TAGS }}
          file: ${{ env.PROJECT }}/Dockerfile
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            MIRROR=${{ vars.MIRRORS }}
            TZ=${{ vars.TZ }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/${{ env.PROJECT }}:buildcache,mode=max
