---
name: Build builder

on:
  push:
    paths:
      - builder/Dockerfile
      - builder/Dockerfile.llvm-mingw64
      - builder/entrypoint.sh
      - builder/resources/**
      - builder/scripts/**
      - .github/workflows/builder.yml

# workflows_run:
#   workflows: [Build baseimage]
#   types:
#     - completed

  workflow_call:

  workflow_dispatch:

env:
  node_version: v24
  go_version: 1.26.7
  rust_version: 1.98.0
  llvm_mingw_version: 20260616

jobs:
  builder:
    name: Build builders
    runs-on: ubuntu-latest
    # 向 buildx 走私 vars/secrets
    env:
      MIRRORS: ${{ vars.MIRRORS }}
      REGISTRY: ${{ vars.REGISTRY }}
      REGISTRY_USER: ${{ vars.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Build ubuntu-24.04 builder
        uses: ./.github/actions/buildx
        with:
          context: builder
          dockerfile: builder/Dockerfile
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-24.04
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-24.04
          args: |
            NODE_VERION=${{ env.node_version }}
            GO_VERSION=${{ env.go_version }}
            RUST_VERSION=${{ env.rust_version }}
            LLVM_MINGW_VERSION=${{ env.llvm_mingw_version }}

      #- name: Build ubuntu-22.04 builder
      #  uses: ./.github/actions/buildx
      #  with:
      #    context: builder
      #    dockerfile: builder/Dockerfile
      #    baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-22.04
      #    tags: |
      #      ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04
      #    args: |
      #      NODE_VERION=${{ env.node_version }}
      #      GO_VERSION=${{ env.go_version }}
      #      RUST_VERSION=${{ env.rust_version }}
      #      LLVM_MINGW_VERSION=${{ env.llvm_mingw_version }}

      - name: Build cygwin64 builder
        uses: ./.github/actions/buildx
        with:
          platforms: linux/amd64
          context: builder
          dockerfile: builder/Dockerfile.cygwin64
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:cygwin64-latest
          args: |
            NODE_VERION=${{ env.node_version }}
            GO_VERSION=${{ env.go_version }}
            RUST_VERSION=${{ env.rust_version }}

      - name: Build mingw64 builder
        uses: ./.github/actions/buildx
        with:
          platforms: linux/amd64
          context: builder
          dockerfile: builder/Dockerfile.llvm-mingw64
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:wine-latest
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:mingw64-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:mingw64-llvm-ucrt
          args: |
            NODE_VERION=${{ env.node_version }}
            GO_VERSION=${{ env.go_version }}
            RUST_VERSION=${{ env.rust_version }}
            LLVM_MINGW_VERSION=${{ env.llvm_mingw_version }}

  full:
    name: Build full builders
    runs-on: ubuntu-latest
    if: ${{ vars.LOCAL_REGISTRY }}
    needs:
      - builder
    strategy:
      matrix:
        include:
          #- baseimage: ubuntu-22.04
          - baseimage: ubuntu-24.04
          - baseimage: mingw64-latest
            platforms: linux/amd64
          - baseimage: cygwin64-latest
            platforms: linux/amd64
    # 向 buildx 走私 vars/secrets
    env:
      MIRRORS: ${{ vars.MIRRORS }}
      REGISTRY: ${{ vars.REGISTRY }}
      REGISTRY_USER: ${{ vars.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Build full builders
        uses: ./.github/actions/buildx
        with:
          platforms: ${{ matrix.platforms }}
          context: builder
          dockerfile: builder/Dockerfile.full
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:${{ matrix.baseimage }}
          tags: |-
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:${{ matrix.baseimage }}-full
