name: Build builder-alpine

on:
  push:
    paths:
      - builder/Dockerfile.alpine
      - builder/entrypoint.sh
      - builder/Implib.so
      - .github/workflows/builder-alpine.yml

# workflows_run:
#   workflows: [Build baseimage-alpine]
#   types:
#     - completed

  workflow_call:

  workflow_dispatch:

jobs:
  build-builder-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        if: ${{ vars.LOCAL_REGISTRY == '' }}
        uses: docker/setup-buildx-action@v3

      - name: Setup buildx (local registry)
        if: ${{ vars.LOCAL_REGISTRY }}
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            debug = true
            [registry."${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."docker.io"]
              mirrors = ["registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.io"]
              mirrors = ["ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.io"]
              mirrors = ["lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: builder
          push: true
          platforms: linux/amd64,linux/arm64
          # https://docs.docker.com/build/ci/github-actions/named-contexts
          build-contexts: |
            alpine:latest=docker-image://${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-latest
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-latest
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-3
          file: builder/Dockerfile.alpine
          build-args: |
            MIRROR=${{ vars.MIRRORS }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:alpine-buildcache,mode=max
