---
name: Build nginx

on:
  push:
    paths:
      - nginx/Dockerfile
      - nginx/rootfs/**
      - .github/workflows/nginx.yml

# workflows_run:
#   workflows: [Build baseimage]
#   types:
#     - completed

  workflow_call:

  workflow_dispatch:
    inputs:
      nginx:
        type: string
        description: nginx version to build

env:
  nginx: 1.30.4

jobs:
  build:
    name: Build nginx
    runs-on: ubuntu-latest

    # 向 buildx 走私 vars/secrets
    env:
      MIRRORS: ${{ vars.MIRRORS }}
      REGISTRY: ${{ vars.REGISTRY }}
      REGISTRY_USER: ${{ vars.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Inspect
        id: inspect
        shell: bash
        run: |-
          version=${{ inputs.nginx }}
          [ -n "$version" ] || version=${{ env.nginx }}

          IFS='=.' read -r m n r <<< "$version"
          test -n "$r" || r=0

          tags=(
            ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:$m.$n.$r
          )

          if [ "$version" = "${{ env.nginx }}" ]; then
            tags+=(
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:latest
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:$m.$n
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:$m
            )
          fi

          {
            echo "tags<<EOF"
            echo "$(printf "%s\n" "${tags[@]}")"
            echo "EOF"
            echo "version=$version"
          } | tee -a $GITHUB_OUTPUT

      - name: Build and Push
        uses: ./.github/actions/buildx
        with:
          context: nginx
          dockerfile: nginx/Dockerfile
          baseimage: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:alpine-latest
          tags: ${{ steps.inspect.outputs.tags }}
          args: |-
            NGX_VER=${{ steps.inspect.outputs.version }}
