---
name: Build nginx

on:
  push:
    paths:
      - nginx/Dockerfile
      - .github/workflows/nginx.yml

# workflows_run:
#   workflows: [Build baseimage]
#   types:
#     - completed

  workflow_call: null

  workflow_dispatch: null

env:
  platforms: linux/amd64,linux/arm64

jobs:
  build-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup buildx
        if: ${{ vars.LOCAL_REGISTRY == '' }}
        uses: docker/setup-buildx-action@v3

      - name: Setup buildx (local registry)
        if: ${{ vars.LOCAL_REGISTRY }}
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            debug = true
            [registry."${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."docker.io"]
              mirrors = ["registry.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."ghcr.io"]
              mirrors = ["ghcr.${{ vars.LOCAL_REGISTRY }}"]
              http = true
            [registry."lscr.io"]
              mirrors = ["lscr.${{ vars.LOCAL_REGISTRY }}"]
              http = true

      - name: Inspect
        id: inspect
        run: |
          docker buildx inspect

          bash --version
          tags() {
            IFS='=' read -r _ v <<< "$(grep 'VERSION=' $1/Dockerfile)"
            IFS='.' read -r m n r <<< "$v"
            t=(
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:latest
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m.$n
            )
            [ -n "$r" ] && t+=(
              ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/$1:$m.$n.$r
            )
            echo "tags=$(tr ' ' ',' <<< "${t[*]}")" | tee -a $GITHUB_OUTPUT
          }

          tags nginx

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: ${{ vars.PUSH_REGISTRY }}
          context: nginx
          file: nginx/Dockerfile
          platforms: ${{ env.platforms }}
          build-contexts: |
            ubuntu:latest=docker-image://${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/baseimage:ubuntu-latest
          tags: ${{ steps.inspect.outputs.tags }}
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/nginx:buildcache,mode=max

  build-nginx-ui:
    uses: ./.github/workflows/nginx-ui.yml
    needs:
      - build-nginx
