---
name: update revisions

on:
  schedule:
    - cron: '0 0 * * *'  # daily

  workflow_dispatch:

jobs:
  try-update-revisions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Prepare
        shell: bash
        run: |
          pwd -P

          git config --global user.name "bot"
          git config --global user.email "bot@mtdcy.top"

      - name: Update Nginx
        run: |-
          set -ex

          bash -c "$(curl -fsSL https://cmdlets.mtdcy.top/latest/cmdlets.sh)" install

          IFS='=.' read -r m n r <<< "$(yq '.env.nginx' .github/workflows/nginx.yml)"

          # update revision only
          if cmdlets.sh install nginx@$m.$n.$((r+1)); then
            r=$((r+1))
          else
            exit 0  # do not return error
          fi

          curl --fail -sL https://nginx.org/en/CHANGES-$m.$n -o nginx/NGX_CHANGES ||
          curl --fail -sL https://nginx.org/en/CHANGES -o nginx/NGX_CHANGES || true

          sed -i .github/workflows/nginx.yml \
            -e "/ *nginx *:[ 0-9.]\+/s/:.*$/: $m.$n.$r/"
          message="update nginx => $m.$n.$r"

          git add nginx .github/workflows/nginx.yml
          git commit -m "$message" || exit 0

      - name: Commit
        shell: bash
        run: |-
          git push
